development:
  adapter: postgresql
  encoding: unicode
  database: hotel_deals_development
  host: localhost
  pool: 5
  username: postgres
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: hotel_deals_test
  host: localhost
  pool: 5
  username: postgres
  password: 123

production:
  adapter: postgresql
  encoding: unicode
  database: hotel_deals_production
  pool: 5
  username: postgres
  password: 123
